### ISSUE TITLE
Is there a recommended way to add your own building + nav + config yamls into a deployment?

### ISSUE THREAD

**Issue by JunHaoChng** [open-rmf/rmf_deployment_template#19]
## Feature request
Ideally, I would like to be able to separate my site specific files (png, config yamls, etc.) from my deployment files. Appreciate any suggestions in advance.

I understand the current way to insert such files is from a [rmf-site.yaml](https://github.com/open-rmf/rmf_deployment_template/blob/cloud_infra/rmf-deployment/templates/rmf-site.yaml) file. But inserting it directly causes a [files too large issue during helm install](https://github.com/prometheus-community/helm-charts/issues/1876), especially when dealing with floorplans of multiple levels. This would require inserting PNGs in the form of binarydumps.

Inserting files from outside helm is [not an option by design](https://github.com/helm/helm/issues/4026). May I ask what would be the recommendation on this?

### Description
In my current setup, I put all such files into the helm charts folder [charts/rmf-core-modules](https://github.com/sharp-rmf/rmf-deployment/tree/galen/rmf-deployment/charts/rmf-core-modules), and I have [configmaps](https://github.com/sharp-rmf/rmf-deployment/tree/galen/rmf-deployment/charts/rmf-core-modules/templates/config) pointing to them. But this gets unmanageable and messy very quickly.

To duplicate the error described above on file being too large, you could run the following in a kubernetes cluster:
```
git clone https://github.com/sharp-rmf/rmf-deployment/tree/galen
mv ./rmf-deployment/charts/rmf-core-modules/* ./rmf-deployment # Agree to overwrite warning
helm install rmf-deployment rmf-core-modules
```
The error:
> Error: create: failed to create: Secret "sh.helm.release.v1.rmf-deployment.v1" is invalid: data: Too long: must have at most 1048576 bytes

### Implementation considerations
To provide a way to manage site specific files without compromising on the continuous deployment aspect.

### Additional information
K8s version: v1.24.4+k3s1
Docker version: Docker version 20.10.16, build aa7e414
RMF version: Following main branch as much as possible

**Comment by JunHaoChng** [comment]
So it's been awhile, I think this can be closed.

Just a note on the above approach, this would imply the git repo would need to be public (there maybe an approach with private repos which I am not aware of). Which may not be suitable for site-specific resources like floorplans.

**Comment by JohnTGZ** [comment]
@JunHaoChng Yes, you can achieve the same thing with private repos too! Most modern CD tools should support SSH/HTTPS Git credentials: https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/
