### ISSUE TITLE
[Other issue]: builder-rosdep.Dockerfile for jazzy

### ISSUE THREAD

**Issue by cwrx777** [open-rmf/rmf_deployment_template#38]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Does [this](https://github.com/open-rmf/rmf_deployment_template/blob/main/rmf/builder-rosdep.Dockerfile#L28-L35) section need to be updated for jazzy?
```bash
RUN if [ "$ROS_DISTRO" = "humble" ]; then \
      apt update && apt install -y \
        clang-13 \
        lldb-13 \
        lld-13 \
        ros-humble-rmw-cyclonedds-cpp \
        && rm -rf /var/lib/apt/lists/* \
      && update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-13 100; \
    fi
```

**Comment by aaronchongth** [comment]
Hi @cwrx777! Yes, it will need to be, if you are using `jazzy`.

For now we would still recommend using `rmw-cyclonedds-cpp` as it has worked well in live environments, but we may revisit the preferred rmw implementation some time soon, especially with our new jazzy releases.

**Comment by cwrx777** [comment]
@aaronchongth how about the compiler?

**Comment by aaronchongth** [comment]
> edit: As for clang usage, although gcc works out of the box with jazzy we have noticed improvements when continuing to use clang, so it will probably remain the default for us

@cwrx777 sorry forgot to post the link where we had this discussion, https://github.com/open-rmf/rmf_ci_templates/pull/10#issuecomment-2130273626

**Comment by akash-roboticist** [comment]
Closing this as the template is now upgraded to support Jazzy
